from node:alpine as build

WORKDIR /usr/src/app

COPY ./ ./

RUN npm install

RUN npm run build



from node:alpine

WORKDIR /usr/src/app

RUN npm install -g http-server

COPY from=build ./public ./

EXPOSE 8080
# Actual script to start can be overridden from `docker run`
CMD ["http-server", "-p", "8080"]
