image: node:8

cache:
  paths:
    - node_modules/

stages:
  - build
  - release
  - deploy

build_vue:
  stage: build
  script:
    - cd vue
    - npm install
    - npm run generate
    - mkdir ../public
    - mv ./dist ../public/vue
  artifacts:
    name: vue-build
    paths:
      - public/vue

.build_react:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
    - mkdir ../public
    - mv ./dist ../public/react
  artifacts:
    name: react-build
    paths:
      - public/react
      
build_html:
  stage: build
  script:
    - echo exporting html
    - mkdir ../public
    - mv html ./public/html
  artifacts:
    name: html-build
    paths:
      - public/html

pages:
  stage: deploy
  script: 
    - echo exporting pages
  artifacts:
    paths:
      - public