image: node:8

cache:
  paths:
    - node_modules/

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE_V1: $CI_REGISTRY_IMAGE:v1
  PRODUCTION_CONTAINER_NAME: www_nickbolles_com
  PRODUCTION_APP_URL: https://$PRODUCTION_DOMAIN

stages:
  - build
  - release
  - deploy

build_v2:
  stage: build
  script:
    - cd v2
    - npm install
    - npm run generate
  artifacts:
    name: v2-build
    paths:
      - v2/dist

.build_react:
  stage: build
  script:
    - cd react
    - npm install
    - npm run build
    - mkdir ../public || true
    - mv ./dist ../public/react
  artifacts:
    name: react-build
    paths:
      - public/react

build_v1:
  stage: build
  script:
    - echo exporting v1-raw
    - mkdir ./public || true
    - mv v1-raw/src ./public/v1
  artifacts:
    name: v1-build
    paths:
      - public/v1

build_docker:
  image: docker:git
  stage: release
  script:
    - setup_docker
    - docker build -t $CONTAINER_RELEASE_IMAGE ./v2/
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    refs:
      - master
      
.build_docker_v1:
  image: docker:git
  stage: release
  script:
    - setup_docker
    - docker build -t $CONTAINER_RELEASE_IMAGE_V1 ./v1
    - docker push CONTAINER_RELEASE_IMAGE_V1
  only:
    refs:
      - master

pages:
  stage: deploy
  script:
    - echo exporting pages
  artifacts:
    paths:
      - public

production:
  image: docker:git
  stage: deploy
  allow_failure: false
  script:
    - setup_docker
    - cleanup_production
    - deploy_production_v2
  environment:
    name: production
    url: $PRODUCTION_APP_URL
  only:
    refs:
      - master

stop_production:
  image: docker:git
  stage: deploy
  when: manual
  allow_failure: false
  script:
    - setup_docker
    - cleanup_production
  environment:
    name: production
    action: stop
  only:
    refs:
      - master

.setup_scripts: &setup_scripts |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x

  # =====Setup Code=====
  function setup_docker() {
    if [[ -n "$CI_JOB_TOKEN" ]]; then
      echo "Logging to GitLab Container Registry with CI Job Token..."
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      echo ""
    fi
  }

  # =====Production Apps=====
  
      #-l 'traefik.portfolio.frontend.priority'="11" \
      #-l 'traefik.portfolio.frontend.redirect.rule'="(.*)portfolio.nickbolles.com(.*)" \
      #-l 'traefik.portfolio.frontend.redirect.replacement'="https://github.com/NickBolles/awesome/blob/master/README.md" \
      #-l 'traefik.resume.frontend.priority'="12" \
      #-l 'traefik.resume.frontend.redirect.rule'="(.*)resume.nickbolles.com(.*)" \
      #-l 'traefik.resume.frontend.redirect.replacement'="https://www.nickbolles.com/Nicholas%20Bolles%20Resume.pdf" \
      
  function deploy_production_v2() {
    # todo: add a weight to Vue and React to do some A/B testing?
    docker run -d --restart='always' \
      -l 'traefik.enable'='true' \
      -l 'traefik.default.frontend.priority'="10" \
      -l 'traefik.default.frontend.rule'="Host:www.$PRODUCTION_DOMAIN,$PRODUCTION_DOMAIN" \
      -l 'traefik.default.port'="8080" \
      -l 'traefik.v2.frontend.priority'="9" \
      -l 'traefik.v2.frontend.rule'="Host:www.$PRODUCTION_DOMAIN,$PRODUCTION_DOMAIN;PathPrefixStrip:/v2/" \
      -l 'traefik.v2.port'="8080" \
      --net='proxied' \
      --name $PRODUCTION_CONTAINER_NAME \
      $CONTAINER_RELEASE_IMAGE
  }
   function deploy_production_old() {
    # todo: add a weight to Vue and React to do some A/B testing?
    docker run -d --restart='always' \
      -l 'traefik.enable'='true' \
      -l 'traefik.v1.frontend.rule'="Host:www.$PRODUCTION_DOMAIN,$PRODUCTION_DOMAIN;PathPrefixStrip:/v1/" \
      -l 'traefik.v1.port'="8080" \
      --net='proxied' \
      --name $PRODUCTION_CONTAINER_NAME \
      $CONTAINER_RELEASE_IMAGE_V1
  }

  function cleanup_production() {
    docker stop $PRODUCTION_CONTAINER_NAME || true
    docker rm $PRODUCTION_CONTAINER_NAME || true
  }

before_script:
  - *setup_scripts
