from node:alpine

WORKDIR /usr/src/app

RUN npm install -g http-server

COPY dist ./

EXPOSE 8080 8081 8082

# Actual script to start can be overridden from `docker run`
CMD ["http-server", "-p", "8080"]
